USE [master]
GO

/****** Object:  Database [Banco]    Script Date: 08/08/2025 21:50:41 ******/
CREATE DATABASE [Banco]
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Banco].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Banco] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Banco] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Banco] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Banco] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Banco] SET ARITHABORT OFF 
GO

ALTER DATABASE [Banco] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Banco] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Banco] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Banco] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Banco] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Banco] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Banco] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Banco] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Banco] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Banco] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Banco] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Banco] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Banco] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Banco] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [Banco] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Banco] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [Banco] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Banco] SET RECOVERY FULL 
GO

ALTER DATABASE [Banco] SET  MULTI_USER 
GO

ALTER DATABASE [Banco] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Banco] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Banco] SET  READ_WRITE 
GO

